version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"

  customers:
    build: ./Customer
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  inventory:
    build: ./Inventory
    ports:
      - "5001:5001"
    depends_on:
      - mysql

  sales:
    build: ./Sales
    ports:
      - "5002:5002"
    depends_on:
      - mysql

  reviews:
      build: ./Reviews
      ports:
        - "5003:5003"
      depends_on:
        - mysql