version: '3.8'
services:
  customer_service:
    build:
      context: ./Customer
    ports:
      - "5000:5000"
    networks:
      - ecommerce_network

  inventory_service:
    build:
      context: ./Inventory
    ports:
      - "5001:5001"
    networks:
      - ecommerce_network

  sales_service:
    build:
      context: ./Sales
    ports:
      - "5003:5003"
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    driver: bridge
