version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"

  customers:
    build: ./customers
    ports:
      - "5000:5000"
    depends_on:
      - mysql